export const treatmentPrices: Record<string, number> = {
  "X exodoncia": 10,
  I_endodoncia: 11,
  caries: 12,
  restauracion_azul: 13,
  O_corona: 14,
  tratamientos: 15,
  restauracion: 16,
  reconstruccion: 17,
  carillas: 18,
  endodoncia_monorradicular: 19,
  endodoncia_multirradicular: 20,
  endodoncia_birradicular: 21,
  exodoncia_simple: 22,
  exodoncia_quirurgica: 23,
  exodoncia_3ros_molares: 24,
  protesis_total_superior: 25,
  protesis_total_inferior: 26,
  protesis_parcial_acrilica_superior: 27,
  protesis_parcial_acrilica_inferior: 28,
  protesis_parcial_flexible_superior: 29,
  protesis_parcial_flexible_inferior: 30,
  protesis_metalica_superior: 31,
  protesis_metalica_inferior: 32,
  corona_impresa_3d: 33,
  corona_zirconio: 34,
  incrustacion_indirecta: 35,
  diseno_sonrisa: 36,
  blanqueamiento: 37,
  tartrectomia_profilaxis: 38,
  frenilectomia: 39,
  gigivectomia: 40,
  ortodoncia: 41,
  implante_dental: 42,
  panoramica: 43,
  rx_periapical: 44,
  escaneo_intraoral: 45,
}

export const treatmentOptions = [
  { value: "X exodoncia", label: "X exodoncia" },
  { value: "I_endodoncia", label: "I endodoncia" },
  { value: "caries", label: "Relleno de zona en rojo caries" },
  { value: "restauracion_azul", label: "Relleno de zona en azul restauración" },
  { value: "O_corona", label: "O corona" },
  { value: "tratamientos", label: "Tratamientos" },
  { value: "restauracion", label: "Restauración" },
  { value: "reconstruccion", label: "Reconstrucción" },
  { value: "carillas", label: "Carillas" },
  { value: "endodoncia_monorradicular", label: "Endodoncia monorradicular" },
  { value: "endodoncia_multirradicular", label: "Endodoncia multirradicular" },
  { value: "endodoncia_birradicular", label: "Endodoncia birradicular" },
  { value: "exodoncia_simple", label: "Exodoncia simple" },
  { value: "exodoncia_quirurgica", label: "Exodoncia quirúrgica" },
  { value: "exodoncia_3ros_molares", label: "Exodoncia 3ros molares" },
  { value: "protesis_total_superior", label: "Prótesis total superior" },
  { value: "protesis_total_inferior", label: "Prótesis total inferior" },
  { value: "protesis_parcial_acrilica_superior", label: "Prótesis parcial acrílica superior" },
  { value: "protesis_parcial_acrilica_inferior", label: "Prótesis parcial acrílica inferior" },
  { value: "protesis_parcial_flexible_superior", label: "Prótesis parcial flexible superior" },
  { value: "protesis_parcial_flexible_inferior", label: "Prótesis parcial flexible inferior" },
  { value: "protesis_metalica_superior", label: "Prótesis metálica superior" },
  { value: "protesis_metalica_inferior", label: "Prótesis metálica inferior" },
  { value: "corona_impresa_3d", label: "Corona impresa 3D" },
  { value: "corona_zirconio", label: "Corona zirconio" },
  { value: "incrustacion_indirecta", label: "Incrustación indirecta" },
  { value: "diseno_sonrisa", label: "Diseño de sonrisa" },
  { value: "blanqueamiento", label: "Blanqueamiento" },
  { value: "tartrectomia_profilaxis", label: "Tartrectomia y profilaxis" },
  { value: "frenilectomia", label: "Frenilectomia" },
  { value: "gigivectomia", label: "Gigivectomia" },
  { value: "ortodoncia", label: "Ortodoncia" },
  { value: "implante_dental", label: "Implante dental" },
  { value: "panoramica", label: "Panorámica" },
  { value: "rx_periapical", label: "Rx periapical" },
  { value: "escaneo_intraoral", label: "Escaneo intraoral" },
]
